#!/usr/bin/env bash

error=0

# Run Go tests
if ! make test; then
	echo "Go tests failed"
	exit 1
fi

# Type check scripts
if ! make check-types; then
	echo "Type checking failed"
	exit 1
fi

# Format Go files
num_fixed_go_files=$(goimports -l . | wc -l)
if [ "$num_fixed_go_files" -gt 0 ]; then
	make format-go
	echo "goimports fixed formatting in $num_fixed_go_files files"
	error=1
fi

# Format JS/TS files
cd injected
if ! yarn prettier -c src; then
	cd ../
	make format-js
	echo "prettier fixed files"
	error=1
fi

exit "$error"